### ISSUE TITLE
./configure changes

### ISSUE THREAD

**Issue by bexelbie** [thejambi/DayJournal#1]
The sources for the build scripts are not in this repo.

Would you consider allowing patches that would optionally not include appindicator3-0.1 for systems that do not use?

Also would you consider allowing a patch to have a binary install only option so that the zero byte AUTHORS ChangeLog NEWS and the non-zero byte but non-documentation files COPYING INSTALL do not get installed?

**Comment by thejambi** [comment]
I could add all my Anjuta workspace files here, but I'm not sure if that would help anyone. Let me know if it would. 

Those suggestions sound great. Thanks!

**Comment by bexelbie** [comment]
I don't use Anjuta, but am not opposed to trying to figure it out :).  I am terribly old skool when it comes to IDEs.  However, I suspect the addition would make it easier for other developers.

As for the configure patches, I'll look into what it takes to get it working.  I am also not an autoconf expert, but I'll spin something up.  Should I email a patch or will you commit them?

**Comment by thejambi** [comment]
I settled on Anjuta because it generates makefiles and tar files and that was the only way I could figure out how to build a .deb package. I just committed all those Anjuta files, so you can take a look. As to what they do, I can't help much with any changes to those at all.

**Comment by bexelbie** [comment]
I'll submit a patch, but I believe you will need to rerun the Makefile creation in Anjuta in order to full merge it.  I've figured out a method that works with automake/aclocal/autoconf which is what I suspect Anjuta is calling on your behalf.

Closing pending patch (which will probably not come today)

**Comment by bexelbie** [comment]
Argh - reopening.

Question: Do you have a desire to begin using the following standard GNU files?  If so, we can populate them and leave them in.  If not, my patch can remove them;

AUTHORS
NEWS
README
INSTALL - right now this is the autoconf default
ChangeLog - it would be nice to have a changelog somewhere
