### ISSUE TITLE
dayjournal.appdata.xml

### ISSUE THREAD

**Issue by bexelbie** [thejambi/DayJournal#3]
Fedora packaging guidelines requirement to provide an appdata.xml file.  See: https://fedoraproject.org/wiki/Packaging:AppData

I am writing one and have two questions:

1. Can I use this for a screenshot? https://burnsoftware.files.wordpress.com/2012/06/dayjournal_screenshot.png  If so, do you mind me committing it to the repo at some point?

2. What is the license for your metadata? CC0-1.0  This would cover things like the screenshots.

**Comment by thejambi** [comment]
Sounds good! CC0-1.0 works for this. Thanks!

**Comment by bexelbie** [comment]
Cool.  I'll close then when I submit the Fedora files.

**Comment by bexelbie** [comment]
PR #5 fixes this.
