### ISSUE TITLE
Blip Sync

### ISSUE THREAD

**Issue by glberen** [thejambi/DayJournal#4]
Hi,

Is there some trick to getting Dayjournal to load Blip entries? I've added the directory path to the Blip journal as <home dir>/Dropbox/apps/Blip Journal, but dayjournal never loads the entries. I've tried escaping the space and even renaming the directory to blip thinking it might have issues parsing the default folder name, but that still hasn't helped. The only indication I receive that dayjournal is even considering the blip entry stuff is an error notification when I attempt to use ~ or an escape (\) in the file url in the config file. 

Any ideas?

Thanks!

**Comment by thejambi** [comment]
Maybe the option to mark the journal that Blip entries are imported to is not set. That's available at the bottom of the journal selection list (the dropdown next to the Open Folder toolbar option). 

You may want to try deleting your config file just to make sure it gets set back to default and try again. It should automatically detect the Blip Journal path correctly.

If that's not the issue, let me know and I'll look into it further if I can. Thanks!

**Comment by glberen** [comment]
It's set. I removed the config, launched to create a default config then I shut the app down, edited the config to put in my Blip path, and fired it up again. Nothing. Is there a log generated somewhere, or a way to enable logging?

**Comment by thejambi** [comment]
You shouldn't have to edit the config file at all. Are you using Blip Journal on iPhone, or Android? 

If Android, how are you getting your files into Dropbox? (I thought it was broken)

When I can, tonight or this weekend hopefully, I'll test it out and let you know if I encounter any of the same issues and how to fix it.

**Comment by glberen** [comment]
I'm using Blip on Android. I use Dropsync to sync the files. That part works great. Thanks for taking a look!

**Comment by thejambi** [comment]
Here's what an example path to one of my Blip Entry files looks like: /home/[yourName]/Dropbox/Apps/Blip Journal/2014/05/21/10_19_26_175.txt

If that is the directory structure you have, then it should be automatic - that's how it's working for me. Maybe you have an extra level of folders in there? Here's a snippet of my config file right after I deleted it, then opened DayJournal again, and it had imported all my Blip Entries:

importJournalDirectory=/home/zach/DayJournal
blipDirectory=/home/zach/Dropbox/Apps/Blip Journal
lastBlipLoadDate=1486608815

So with the directory structure example I gave, that's what the blipDirectory should be set to. If you have a lastBlipLoadDate, you should be able to delete it or set it to 0, and then when you open DayJournal, it should add all your entries.

Let me know if there are still issues. If so, maybe send your entire config file and some example file paths to Blip entry files.

**Comment by glberen** [comment]
When I launch dj from the command line, I'm able to see some errors logged out to the console. Here's one: 

** (dayjournal:4545): CRITICAL **: file BlipLoader.c: line 1527: uncaught error: Error opening directory '/home/bgreen/Dropbox/Apps/Day One/Journal.dayone/entries': No such file or directory (g-io-error-quark, 1)

Where is dj getting that Day One path from? I'm not using Day One. 

I get this on a brand-new install, with the config wiped.

Here's the pathing for the Blip stuff:

/home/bgreen/Dropbox/apps/blip/2017/02/09

With files like the below within the directory: 

16_58_27_734.txt

This is the entirety of the config:

[DayJournal]
importJournalDirectory=/home/bgreen/DayJournal
blipDirectory=/home/bgreen/Dropbox/apps/Blip Journal
width=604
height=491

[Journals]
/home/bgreen/DayJournal=/home/bgreen/DayJournal

I had to fill in the Blip directory because it wasn't getting populated.

**Comment by thejambi** [comment]
Okay, it looks like your blipDirectory path should be set to this: /home/bgreen/Dropbox/apps/blip

with "blip" on the end, instead of "Blip Journal" on the end.

**Comment by glberen** [comment]
I created a /home/bgreen/Dropbox/apps/blip directory and copied the files from ../apps/Blip Journal to there with the same results. I tried that early on thinking the space in the filename wasn't getting parsed correctly, but it still has the same results.

I have duplicate paths for both blip and Blip Journal.  

Sorry, the pathing I pasted in above should've been /home/bgreen/Dropbox/apps/Blip Journal/2017/02/09

**Comment by thejambi** [comment]
Oh, ok. I think I see what the problem is... I'm working on it!

I think it must be the Day One file check. So to get it to work, create these directories:

/home/bgreen/Dropbox/Apps/Day One/Journal.dayone/entries/
/home/bgreen/Dropbox/Apps/Day One/Journal.dayone/photos/

Sorry about that.

**Comment by thejambi** [comment]
The [DayJournal](https://burnsoftware.wordpress.com/dayjournal/) page has been updated with a link to the latest version with the fix for this. I can't update to the PPA anymore because latest versions of the tools I used to build have broken my previous process. So you'll need to download the installer, and also the launcher and icon if you need them. Links are near the top of the [DayJournal](https://burnsoftware.wordpress.com/dayjournal/) page.

**Comment by glberen** [comment]
Ok, thanks. I'll give the new vesion a try. I think there's also going to be a case conflict though. I have an existing apps directory in dropbox. The file URL being checked is ../Dropbox/Apps. There may be a problem with interpreting that in certain cases perhaps. 

I created a symlink Apps to point to apps, so maybe it'll work. I'll update in a moment.

**Comment by glberen** [comment]
Well, the Day One error is gone after creating the directories. The only error I'm seeing in the console for the new version is this:

(dayjournal:12877): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuButton

Still no import, however. 

Config used against the new version: 

[DayJournal]
importJournalDirectory=/home/bgreen/DayJournal
blipDirectory=/home/bgreen/Dropbox/apps/Blip Journal
lastBlipLoadDate=0
width=1143
height=1021

[Journals]
/home/bgreen/DayJournal=/home/bgreen/DayJournal


After the above, I copied my Blip Journal directory from Dropbox to my home folder and named it blip. Then I changed the config to point the blip directory to /home/bgreen/blip

No import, but a lot of errors:

** (dayjournal:13735): CRITICAL **: blip_data_construct: assertion 'dateTime != NULL' failed

(dayjournal:13735): GLib-CRITICAL **: g_date_time_get_hour: assertion 'datetime != NULL' failed

(dayjournal:13735): GLib-CRITICAL **: g_date_time_format: assertion 'datetime != NULL' failed

** (dayjournal:13735): CRITICAL **: blip_data_construct: assertion 'dateTime != NULL' failed

(dayjournal:13735): GLib-CRITICAL **: g_date_time_get_hour: assertion 'datetime != NULL' failed

(dayjournal:13735): GLib-CRITICAL **: g_date_time_format: assertion 'datetime != NULL' failed

** (dayjournal:13735): CRITICAL **: blip_data_construct: assertion 'dateTime != NULL' failed

(dayjournal:13735): GLib-CRITICAL **: g_date_time_get_hour: assertion 'datetime != NULL' failed

(dayjournal:13735): GLib-CRITICAL **: g_date_time_format: assertion 'datetime != NULL' failed

** (dayjournal:13735): CRITICAL **: blip_data_construct: assertion 'dateTime != NULL' failed

(dayjournal:13735): GLib-CRITICAL **: g_date_time_difference: assertion 'begin != NULL' failed

(dayjournal:13735): GLib-CRITICAL **: g_date_time_get_hour: assertion 'datetime != NULL' failed

(dayjournal:13735): GLib-CRITICAL **: g_date_time_format: assertion 'datetime != NULL' failed

** (dayjournal:13735): CRITICAL **: blip_data_construct: assertion 'dateTime != NULL' failed

(dayjournal:13735): GLib-CRITICAL **: g_date_time_get_hour: assertion 'datetime != NULL' failed

(dayjournal:13735): GLib-CRITICAL **: g_date_time_format: assertion 'datetime != NULL' failed

** (dayjournal:13735): CRITICAL **: blip_data_construct: assertion 'dateTime != NULL' failed

** (dayjournal:13735): CRITICAL **: __lambda7_: assertion 'blip != NULL' failed

** (dayjournal:13735): CRITICAL **: __lambda7_: assertion 'blip != NULL' failed

** (dayjournal:13735): CRITICAL **: __lambda7_: assertion 'blip != NULL' failed

** (dayjournal:13735): CRITICAL **: __lambda7_: assertion 'blip != NULL' failed

** (dayjournal:13735): CRITICAL **: __lambda7_: assertion 'blip != NULL' failed

** (dayjournal:13735): CRITICAL **: __lambda7_: assertion 'blip != NULL' failed

** (dayjournal:13735): CRITICAL **: __lambda7_: assertion 'blip != NULL' failed

** (dayjournal:13735): CRITICAL **: blip_data_addToCorrespondingEntryIfBetweenDates: assertion 'self != NULL' failed

** (dayjournal:13735): CRITICAL **: blip_data_addToCorrespondingEntryIfBetweenDates: assertion 'self != NULL' failed

** (dayjournal:13735): CRITICAL **: blip_data_addToCorrespondingEntryIfBetweenDates: assertion 'self != NULL' failed

** (dayjournal:13735): CRITICAL **: blip_data_addToCorrespondingEntryIfBetweenDates: assertion 'self != NULL' failed

** (dayjournal:13735): CRITICAL **: blip_data_addToCorrespondingEntryIfBetweenDates: assertion 'self != NULL' failed

** (dayjournal:13735): CRITICAL **: blip_data_addToCorrespondingEntryIfBetweenDates: assertion 'self != NULL' failed

**Comment by thejambi** [comment]
Hm. Could you maybe make some testing Blip Entries and sync them to dropbox, then compress them from the root Blip Journal dir and send them to me? I'd like to see if they would work for me. The paths look right, but maybe I'm missing something.

**Comment by glberen** [comment]
[blip_entries.tar.gz](https://github.com/thejambi/DayJournal/files/769718/blip_entries.tar.gz)

Here you go. Thanks!

**Comment by thejambi** [comment]
Thanks. I think I was able to fix it. Please download [the latest version](https://www.dropbox.com/s/7d6e8fqb6g6frwk/dayjournal_23.0.8-1_amd64.deb?dl=0) to install it and try again.

**Comment by glberen** [comment]
Yep, that works! Thank you so much!
