### ISSUE TITLE
Fedora Packaging code removed

### ISSUE THREAD

**Issue by bexelbie** [thejambi/DayJournal#7]
Why was the Fedora packaging code dropped from the upstream?

**Comment by thejambi** [comment]
Sorry about that, they got caught in a cleanup of things.. I got them back. Let me know if anything in the fedora folder is dependent on something else that was removed from elsewhere.

**Comment by bexelbie** [comment]
Will do. I'll also try to eliminate any of them I can based on the new files - wont have a chance to do this before late next week though.
